# Generated by Django 5.1.1 on 2024-10-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_usertextassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertextassignment',
            name='assigned_list_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
