# Generated by Django 5.1.1 on 2024-10-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_usertextassignment_assigned_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertextassignment',
            name='assigned_list_id',
        ),
    ]
