# Generated by Django 5.1.1 on 2024-10-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_clues_alter_profile_clue_solved_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clues',
            name='solved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
