# Generated by Django 5.1.1 on 2024-10-16 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finish',
            name='timeout',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
