# Generated by Django 5.1.1 on 2024-10-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_alter_finish_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertextassignment',
            name='assigned_text',
            field=models.CharField(max_length=350),
        ),
    ]
