# Generated by Django 5.1.1 on 2024-10-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_alter_usertextassignment_assigned_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertextassignment',
            name='assigned_text',
            field=models.TextField(max_length=350),
        ),
    ]
