# Generated by Django 5.1.1 on 2024-10-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_alter_usertextassignment_assigned_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Clues',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
